enum STATE {
  STARTING_UP,
  WAITING_FOR_BOUNCE,
  DEBOUNCING,
  CHECKING_RESULT,
  RESTARTING,
  ENDING_PROGRAM,
  EMERGENCY_STOP  };

enum EVENT_TYPE {       //TODO make system transition event types
  SYSTEM_EVENT,
  STATE_CHANGE,
  LIGHT_SENSOR_FALLING_EDGE_EVENT,
  FLOOR_SENSOR_EVENT,
  SERVO_OPEN_EVENT,
  SERVO_CLOSE_EVENT,
  ALARM_EVENT };

enum SERVO_COMMAND { OPEN, CLOSE }; // used to communicate to servo function
